### ISSUE TITLE
index.html & missing images

### ISSUE THREAD

**Issue by nscarlyon** [learn-co-curriculum/css-kitten-wheelbarrow#5]
Hello, I apologize in advance if this is something you are already working on or perhaps I did something wrong on my part. I noticed a few issues with this particular lab:

1) When I forked & cloned the master, there was literally nothing in the index.html file. At first, I thought I would find further instruction on what to type in the file, but there were no instructions, so I just copied the index solution code from the Learn Master branch and pasted it into my local index.html file. 

2) None of the images (kitty-1....) would display in any of my browsers (ie, firefox, and chrome) or my image viewers. This is the first time I had problems with seeing images in a lab. There could be something wrong with my browsers.

3) I really appreciated how previous labs had a snapshot of what the final outcome should look like. Since there was no such image, I wasn't exactly sure if I got the desired effect. I believe future users would benefit from seeing an image of what the page should look like.

That is all. I have really been enjoying all the labs so far.=)

**Comment by AnnJohn** [comment]
hi @nscarlyon sorry for the trouble that you're having. This looks like a technical issue instead of a curriculum issue since everything looks up to date on the Learn Master branch. 

I'm going to close this issue here but can you please file a bug report? If you hover over your profile pic in Learn, you should see a menu with an option to Report a Bug. 

Also, could you please use the Ask a Question tool so that one of our Learn Experts can help you debug this specific problem? 

Thanks!
