### ISSUE TITLE
Problem with Forking this Lesson

### ISSUE THREAD

**Issue by MysticRiver** [learn-co-curriculum/css-kitten-wheelbarrow#6]
There is a problem forking this lesson.
All of the files are empty/blank and the images are 0 bytes and will not load.
I'm unable to complete the lesson as a result of this.

**Comment by AnnJohn** [comment]
hi @MysticRiver I'll keep this issue open here to try to replicate your error but if you can, can you also file a bug report as well so that our product team is aware as this is a technical issue. If you hover over your profile pic in Learn, you'll see an option to 'Report a Bug' from the dropdown menu that appears
